### ISSUE TITLE
ESM ignores environment variables defined in the "manifest_content" section

### ISSUE THREAD

**Issue by franciscoRdiaz** [elastest/elastest-service-manager#17]
Hi Andy,

I am trying to provide an EMS TSS using the ESM and I can see, that the environment variables defined in the "manifest_content" section are ignored

It would be convenient to keep these environment variables.

Is it possible?

At this moment, the elasticsearch that start up the EMS does not work for this reason.

Thanks.

**Comment by dizz** [comment]
@franciscoRdiaz can you ping me on slack or provide here further details on your expectations of functionality?
