### ISSUE TITLE
Environment variables defined in the docker-compose file do not apper inside the container....

### ISSUE THREAD

**Issue by franciscoRdiaz** [elastest/elastest-service-manager#21]
Hi,

I have the following issue. I have defined the environment variable "- ET_DOCKER_IMG_NOVNC=elastest/eus-novnc:latest\n" in the docker-compose of the EUS, but this variable does not appear when I do print env inside the Eus container.
So I think the reason for this is the environment variables sent in the "paramenters" request field  override the environment variables defined in the docker-compose file.

I have attched the following files:
- content of the elastestservice.json file of the EUS
[eus-elastestservice-json.txt](https://github.com/elastest/elastest-service-manager/files/1736136/eus-elastestservice-json.txt)

- Environment variables inside the EUS's container
[eus-container-environment-var.txt](https://github.com/elastest/elastest-service-manager/files/1736148/eus-container-environment-var.txt)

- Pircture of manifest stored by the ESM and retrived by the ESM API
![esm-api-retrieved-manifest](https://user-images.githubusercontent.com/24293824/36371371-308e0c24-1562-11e8-8233-7dac2bc936c8.jpg)

Thanks.

**Comment by dizz** [comment]
Hey @franciscoRdiaz  - I’ve tested with the docker-compose file that was contained in your elastestservice.json file, and I cannot reproduce the issue. Once the container is provisioned, this is the set of shell environment variables:

```
docker exec -t -i 58392761b708 sh              
/ # env
JAVA_ALPINE_VERSION=8.151.12-r0
HOSTNAME=58392761b708
SHLVL=1
HOME=/root
JAVA_VERSION=8u151
ET_DOCKER_IMG_NOVNC=elastest/eus-novnc:latest
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
LANG=C.UTF-8
USE_TORM=true
PWD=/
JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre
/ # 
```

Note `ET_DOCKER_IMG_NOVNC=elastest/eus-novnc:latest` present in the output.
