### ISSUE TITLE
All API methods return the same message

### ISSUE THREAD

**Issue by franciscoRdiaz** [elastest/elastest-service-manager#6]
Hi ,

We are trying to integrate all modules of ElasTest and therefore we have deployed the ESM. When we try to use the API, either from the code or from the URL http://192.168.99.100:8080/ui/, it always returns us the following message:

"No X-Broker-Api-Version header supplied in the request. This endpoint supports 2.12."

Have you ever seen this message?
Any idea what the problem might be?

Thank you.

**Comment by dizz** [comment]
All endpoints by default require the OSBA version header `X-Broker-Api-Version`. This should have the value of `2.12`. For curl [examples see here](https://github.com/elastest/elastest-service-manager/blob/master/docs/index.md#basic-usage)

**Comment by franciscoRdiaz** [comment]
Hi,

I have tried it and it worked well.

Thank you.

**Comment by dizz** [comment]
No prob! 👍
